services:
    moomoo_condition.registry.conditions:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Registry\ConditionsRegistry'

    moomoo_condition.command.conditions_list:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Command\ConditionsListCommand'
        arguments:
            - '@moomoo_condition.registry.conditions'
        tags:
            - { name: moomoo_wpcli_command }