services:
    moomoo_condition.registry.conditions:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Registry\ConditionsRegistry'

    moomoo_condition.is_gutenberg:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\FunctionExistsCondition'
        arguments:
            - name: is_gutenberg
              function: register_block_type
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_singular:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\SimpleCondition'
        arguments:
            - name: is_post_exists
              function: is_singular
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_user_logged_in:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\SimpleCondition'
        arguments:
            - name: is_user_logged_in
              function: is_user_logged_in
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_user_not_logged_in:
        parent: moomoo_condition.is_user_logged_in
        calls:
            - [setName, [is_user_not_logged_in]]
            - [setValidResult, [false]]
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_backend:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\SimpleCondition'
        arguments:
            - name: is_backend
              function: is_admin
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_frontend:
        parent: moomoo_condition.is_backend
        calls:
            - [setName, [is_frontend]]
            - [setValidResult, [false]]
            - [addDependOnCondition, ['@moomoo_condition.is_not_customize_preview']]
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_customize_preview:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\SimpleCondition'
        arguments:
            - name: is_customize_preview
              function: is_customize_preview
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_not_customize_preview:
        parent: moomoo_condition.is_customize_preview
        calls:
            - [setName, [is_not_customize_preview]]
            - [setValidResult, [false]]
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_post_create_page:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\IsPostEditPageCondition'
        arguments:
            - name: is_post_create_page
              arguments:
                  action: 'new'
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_post_edit_page:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\IsPostEditPageCondition'
        arguments:
            - name: is_post_edit_page
              arguments:
                  action: 'edit'
        tags:
            - {name: moomoo_condition}

    moomoo_condition.is_post_create_or_edit_page:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\IsPostEditPageCondition'
        arguments:
            - name: is_post_create_or_edit_page
        tags:
            - {name: moomoo_condition}
