services:
    moomoo_condition.is_backend:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\IsBackendCondition'

    moomoo_condition.is_frontend:
        parent: moomoo_condition.is_backend
        calls:
            - [setValidResult, [false]]

    moomoo_condition.is_post_create_page:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\IsPostEditPage'
        arguments:
            - 'new'

    moomoo_condition.is_post_edit_page:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\IsPostEditPage'
        arguments:
            - 'edit'

    moomoo_condition.is_post_create_or_edit_page:
        class: 'MooMoo\Platform\Bundle\ConditionBundle\Model\IsPostEditPage'