services:
    moo_meta_box.registry.meta_boxes:
        class: 'MooMoo\Platform\Bundle\MetaBoxBundle\Registry\MetaBoxesRegistry'

    moo_meta_box.registrator.meta_boxes:
        class: 'MooMoo\Platform\Bundle\MetaBoxBundle\Registrator\MetaBoxesRegistrator'