services:
    moo_post.registry.post_types:
        class: 'MooMoo\Platform\Bundle\PostBundle\PostType\Registry\PostTypesRegistry'

    moo_post.registrator.post_types:
        class: 'MooMoo\Platform\Bundle\PostBundle\PostType\Registrator\PostTypesRegistrator'
