services:
    moomoo_post.registry.post_types:
        class: 'MooMoo\Platform\Bundle\PostBundle\PostType\Registry\PostTypesRegistry'
        public: true

    moomoo_post.registrator.post_types:
        class: 'MooMoo\Platform\Bundle\PostBundle\PostType\Registrator\PostTypesRegistrator'
        public: true
