services:
    moomoo_wpcli.registry.commands:
        class: 'MooMoo\Platform\Bundle\WpCliBundle\Registry\WpCliCommandsRegistry'
        public: true

    moomoo_wpcli.registrator.commands:
        class: 'MooMoo\Platform\Bundle\WpCliBundle\Registrator\WpCliCommandsRegistrator'
        public: true
